<a href="https://colab.research.google.com/github/ArianaMedina85/python/blob/main/Clase_NumpyTec2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Inteligencia Artificial Aplicada (2025)

Esta unidad se presentan distintos módulos en Python que facilitan la manipulación y mejoran la eficiencia al implementar funciones estadísticas y modelos matemáticos sobre un gran número de datos. Así mismo, se presentan módulos en Python que permiten hacer cálculos numéricos en unidades de procesamiento gráficos de propósito general (GPGPU’s, por sus siglas en inglés), y, en consecuencia, realizar un gran número de operaciones matemáticas y cálculos estadísticos de forma paralela.

### Importamos numpy ###

In [1]:
# Importamos numpy
import numpy as np

### Seguimos con índices de numpy: Booleanos como índices ###

En algunos casos resulta útil seleccionar elementos en función de que cumplan algún condicional. Supongamos por ejemplo que tenemos un arreglo que contiene los tiempos registrados por las corredoras de 100 mts del equipo del IPICYT. Como no podemos guardar arreglos más que con un tipo de información (por las características de numpy), vamos a generar dos arreglos, uno con nombres y otro con los 5 últimos tiempos registrados. Cada uno de los renglones corresponde al registro de los nombres, considerando el mismo orden en que aparecen en el arreglo.

In [ ]:
nombres = np.array(["Lisa", "Margaret", "Marjorie", "Patricia", "Marjorie"])
tiempos = np.array([[11.09, 11.2, 11.12, 11.23, 11.21],
                   [11.12, 11.17, 11.16, 11.13, 11.18],
                   [11.04, 11.10, 11.06, 11.08, 11.04],
                   [11.25, 11.27, 11.27, 11.29, 11.21],
                   [11.29, 11.32, 11.3, 11.31, 11.31]])

Puedo utilizar condicionales para generar un arreglo de booleanos

In [ ]:
print(nombres == "Marjorie")
print()
print(tiempos < 11.10)

[False False  True False  True]

[[ True False False False False]
 [False False False False False]
 [ True False  True  True  True]
 [False False False False False]
 [False False False False False]]


pero aún más interesante es que puedo utilizar el arreglo de booleanos para seleccionar elementos de otro arreglo (funcionan como una especie de apagador). __OJO__ las dimensiones del arreglo índice y del arreglo del cual selecciono elementos, deben coincidir.

In [ ]:
print(nombres == "Marjorie")
print()
print(tiempos)
print()
print(tiempos[nombres == "Marjorie"]) #escoge los rangos o intervalos se escogen

[False False  True False  True]

[[11.09 11.2  11.12 11.23 11.21]
 [11.12 11.17 11.16 11.13 11.18]
 [11.04 11.1  11.06 11.08 11.04]
 [11.25 11.27 11.27 11.29 11.21]
 [11.29 11.32 11.3  11.31 11.31]]

[[11.04 11.1  11.06 11.08 11.04]
 [11.29 11.32 11.3  11.31 11.31]]


In [2]:
print(tiempos)
print()
print(nombres != "Marjorie")
print()
print(tiempos[nombres != "Marjorie"])

NameError: name 'tiempos' is not defined

In [ ]:
print(tiempos)
print()
print(tiempos  < 11.10)
print()
print(tiempos[tiempos < 11.10])

[[11.09 11.2  11.12 11.23 11.21]
 [11.12 11.17 11.16 11.13 11.18]
 [11.04 11.1  11.06 11.08 11.04]
 [11.25 11.27 11.27 11.29 11.21]
 [11.29 11.32 11.3  11.31 11.31]]

[[ True False False False False]
 [False False False False False]
 [ True False  True  True  True]
 [False False False False False]
 [False False False False False]]

[11.09 11.04 11.06 11.08 11.04]


__Ejercicio__ Utilizando numpy y el indizado con booleanos, despliega los valores del arreglo que sean positivos.

In [ ]:
a = np.random.rand(6,6)-0.5 #genera numeros entre numeros de 0 y 1 en un arreglo de 6x6 y le quita 0.5 : -0.5  a 0.5
print(a > 0)
print(a[ a>0])


# Tu respuesta aquí



[[ True False  True  True False False]
 [False  True  True False False  True]
 [False  True  True False  True False]
 [False False False  True False False]
 [ True  True False False  True False]
 [ True False  True  True  True  True]]
[0.11259957 0.30858657 0.31045071 0.30547343 0.11992129 0.13580656
 0.39313476 0.12338306 0.48173036 0.37258528 0.40709578 0.3547795
 0.0013651  0.01068525 0.40454685 0.42875613 0.43200724 0.36767362]


### Seguimos con índices de numpy: Fancy indexing ###

En numpy se pueden utilizar arreglos de enteros como índices, y a esta idea es a la que se le llama _Fancy indexing_.

__Ejemplo__ , Utilicemos una lista y un ndarray para seleccionar elementos de un arreglo de numpy (ndarray).

In [ ]:
# Primero hacemos una lista de los primeros 5 números naturales impares

lista = [i for i in range(1,10,2)]
print(lista)


[1, 3, 5, 7, 9]


In [ ]:
# Luego hacemos un ndarray de los primeros 5 números naturales pares (cast)

ndarr = np.array([i for i in range(0,10,2)])
print(ndarr)


[0 2 4 6 8]


In [ ]:
# Finalmente, hacemos un arreglo de numpy de 10x5 donde cada renglón corresponda a un número entero distinto
# Observar el uso anidado de list comprehension

arreglonp = np.array([[i + j*0.1 for j in range(5)] for i in range(10)])
print(arreglonp, type(arreglonp))


[[0.  0.1 0.2 0.3 0.4]
 [1.  1.1 1.2 1.3 1.4]
 [2.  2.1 2.2 2.3 2.4]
 [3.  3.1 3.2 3.3 3.4]
 [4.  4.1 4.2 4.3 4.4]
 [5.  5.1 5.2 5.3 5.4]
 [6.  6.1 6.2 6.3 6.4]
 [7.  7.1 7.2 7.3 7.4]
 [8.  8.1 8.2 8.3 8.4]
 [9.  9.1 9.2 9.3 9.4]] <class 'numpy.ndarray'>


Utilicemos la selección para obtener renglones con índices pares e impares

In [ ]:
# Primero impares
impares = arreglonp[[1, 3, 5, 7, 9]]
print(impares)


[[1.  1.1 1.2 1.3 1.4]
 [3.  3.1 3.2 3.3 3.4]
 [5.  5.1 5.2 5.3 5.4]
 [7.  7.1 7.2 7.3 7.4]
 [9.  9.1 9.2 9.3 9.4]]


In [ ]:
# Después pares
ndarr = np.array([i for i in range(0,10,2)])
print(ndarr, type(ndarr))

#pares = arreglonp[ndarr]
pares = arreglonp[[0, 2, 4, 6, 8]]
#pares = arreglonp[(0, 0)] # Ojo, una tupla como argumento representa otra cosa
print(pares)


[0 2 4 6 8] <class 'numpy.ndarray'>
[[0.  0.1 0.2 0.3 0.4]
 [2.  2.1 2.2 2.3 2.4]
 [4.  4.1 4.2 4.3 4.4]
 [6.  6.1 6.2 6.3 6.4]
 [8.  8.1 8.2 8.3 8.4]]


También podemos utilizar combinaciones de enteros para seleccionar, como parejas de enteros en el caso de tener un arreglo de dos dimensiones.

In [ ]:
arreglonp = np.array([[i + j*0.1 for j in range(5)] for i in range(10)])
#print(arreglonp, type(arreglonp))

print(arreglonp)
print()

print("Ahora los elementos de una diagonal:\n")

diagonal = arreglonp[[0,1,2,3],[1,2,3,4]]
print(diagonal)
print()


[[0.  0.1 0.2 0.3 0.4]
 [1.  1.1 1.2 1.3 1.4]
 [2.  2.1 2.2 2.3 2.4]
 [3.  3.1 3.2 3.3 3.4]
 [4.  4.1 4.2 4.3 4.4]
 [5.  5.1 5.2 5.3 5.4]
 [6.  6.1 6.2 6.3 6.4]
 [7.  7.1 7.2 7.3 7.4]
 [8.  8.1 8.2 8.3 8.4]
 [9.  9.1 9.2 9.3 9.4]]

Ahora los elementos de una diagonal:

[0.1 1.2 2.3 3.4]



In [ ]:
# OJO
diagonal2 = arreglonp[[0,0]]
print(diagonal2)
print()

# Así que:
diagonal2 = arreglonp[[0,1,2],[0,1,2]]
print(diagonal2)
print()

[[0.  0.1 0.2 0.3 0.4]
 [0.  0.1 0.2 0.3 0.4]]

[0.  1.1 2.2]



__Ejercicio__ Utilizando numpy y fancy indexing, selecciona los elementos de la última columna del siguiente arreglo

In [ ]:
b = np.random.rand(6,6)
print(b)
print()
# Tu respuesta aquí


[[0.00293829 0.15344523 0.99815894 0.69290942 0.78231093 0.17136056]
 [0.89071857 0.4717294  0.48719724 0.0349015  0.458763   0.14578299]
 [0.07936404 0.80604835 0.04725632 0.86071242 0.08078201 0.89435777]
 [0.3791029  0.26244011 0.36008457 0.98376167 0.31574338 0.69721258]
 [0.39305284 0.46400617 0.96874626 0.29026313 0.23168403 0.29590992]
 [0.1476195  0.02139303 0.56080618 0.19649155 0.22524187 0.94778919]]

[0.17136056 0.14578299 0.89435777 0.69721258 0.29590992 0.94778919]


### Funciones universales ###

Las _ufunc_ o _funciones universales_ son funciones que operan sobre arreglos de numpy, y que operan bajo la lógica de elemento-a-elemento.

Existen funciones ufunc unarias binarias, es decir, que operan sobre uno o dos argumentos, respectivamente.

__Ejemplos__ con operadores unarios

In [ ]:
# Creamos un arreglo
ar1 = np.arange(1,50,2)
print(ar1)
print("Arreglo al cuadrado")
# Elevo al cuadrado
ar2 = ar1*ar1
print(ar2)
# Raiz cuadrada de los elementos
print("\nUtilizando la ufunc sqrt ... ")
print(np.sqrt(ar2))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Arreglo al cuadrado
[   1    9   25   49   81  121  169  225  289  361  441  529  625  729
  841  961 1089 1225 1369 1521 1681 1849 2025 2209 2401]

Utilizando la ufunc sqrt ... 
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49.]


In [ ]:
# Creamos un arreglo
ar1 = np.arange(1,20,2)
print("Arreglo inicial")
print(ar1)
# Logaritmo natural de cada uno de los elementos
print("\nUtilizando la ufunc log ... ")
print(np.log(ar1))

#import math
#print(math.log(ar1))

Arreglo inicial
[ 1  3  5  7  9 11 13 15 17 19]

Utilizando la ufunc log ... 
[0.         1.09861229 1.60943791 1.94591015 2.19722458 2.39789527
 2.56494936 2.7080502  2.83321334 2.94443898]


__Ejemplos__ , ahora con operadores binarios

In [ ]:
# Creamos dos arreglos
ar1 = np.random.rand(1,5)
ar2 = np.random.rand(5)
print("Arreglo 1")
print(ar1)
print("\nArreglo 2")
print(ar2)

# Obtengo el máximo entre ambos arreglos
print("\nUtilizando la ufunc maximum ... ")
print(np.maximum(ar1, ar2))

Arreglo 1
[[0.72520434 0.20057892 0.82980098 0.2985277  0.008163  ]]

Arreglo 2
[0.1379919  0.0105777  0.87521014 0.70952412 0.06223885]

Utilizando la ufunc maximum ... 
[[0.72520434 0.20057892 0.87521014 0.70952412 0.06223885]]


__NOTA:__

Se conoce como _vectorización_ a la práctica de reemplazar ciclos explícitos con expresiones que operan sobre arreglos; esto es el núcleo de numpy. Estas operaciones sobre arreglos vectorizadas, suelen ser mucho más rápidas (la diferencia medida en órdenes de magnitud) que sus contrapartes de Python normal.

### Estadística básica trabajando arreglos ###

Numpy incluye una gran cantidad de funciones matemáticas estadísticas que pueden operar
sobre todos los elementos de un arreglo, o sobre los datos a lo largo de un eje en particular. Veamos un ejemplo.

In [ ]:
# Genero datos aleatorios con numpy.random
data = np.random.randn(6,5)
print(data)

[[-0.57300814 -0.74172803  1.16642196 -0.51492051  0.942132  ]
 [-1.47206203 -0.11579901  1.77868554  0.33179292  1.01632152]
 [ 0.63826833  0.77276713 -0.23773847  1.99679214 -0.02221132]
 [-1.91695883 -0.92163016  0.48956214 -1.22871514  1.77706472]
 [ 2.76032782 -0.56553795 -0.88722248 -0.45310488 -0.98356081]
 [ 0.99618273 -0.04837662 -1.25970725  0.5290228   1.13271214]]


Podemos obtener el promedio sobre todo el conjunto de datos

In [ ]:
print(np.mean(data))

0.14619240882014015


O podemos obtener el promedio sobre uno de los ejes en particular

In [ ]:
data = np.random.randn(6,5)
print(data)
print()
# obtengo promedio sobre el primer eje
print("Esto resulta de promediar sobre el primer eje")
print(np.mean(data, axis=0).shape)
print(np.mean(data, axis=0))
print()
# obtengo promedio sobre el segundo eje
print("Esto resulta de promediar sobre el segundo eje")
print(np.mean(data, axis=1).shape)
print(np.mean(data, axis=1))

[[-0.58213987 -0.19728601 -1.53988799 -1.03676869 -0.93942615]
 [ 0.52205875 -1.38602354  0.65216536  0.94549196  1.23209559]
 [-0.01417166  1.1978055  -1.37680779 -0.42292206 -0.26735207]
 [ 0.26966948  0.58157022  0.79371049  0.17813088  1.78617679]
 [ 0.40237062 -0.29062681  0.97932548 -0.92216188 -0.1688143 ]
 [ 0.43549944 -0.00993607  0.79700174  0.98731948  0.01351229]]

Esto resulta de promediar sobre el primer eje
(5,)
[ 0.17221446 -0.01741612  0.05091788 -0.04515172  0.27603202]

Esto resulta de promediar sobre el segundo eje
(6,)
[-8.59101743e-01  3.93157625e-01 -1.76689617e-01  7.21851571e-01
  1.86214437e-05  4.44679378e-01]


__Ejercicio__ Utilizando numpy y el arreglo _data_, obtén:

* El promedio sobre los 15 números que se obtienen a partir de la 3era columna y del segundo renglón. En términos de índices, se trata de los elementos (3,2), (3,3), (3,4), (3,5), (4,2), (4,3), etc.
* El promedio para cada renglón, quitando la primera columna

In [ ]:
# Tus respuestas aquí

# Primer inciso

# Segundo inciso


[[ 1.40708738  0.49463873 -0.03239417 -0.12109167  1.73634878]
 [-0.90315788  1.32470889 -0.58740208  0.60085391 -0.33236538]
 [ 0.76498344 -0.04056702 -0.95513725  0.9286182   0.62451984]
 [ 1.48194241  0.02199373 -0.03689571  1.57001776  0.20057556]
 [ 0.22923079 -0.36108241  0.77322521 -0.47056187  0.19962761]
 [-0.04936248 -0.2032522   0.82921193  0.88782624 -0.11569695]]



In [ ]:
# Genero datos aleatorios con numpy.random
data = np.random.randn(6,5)
print(data)

[[ 0.14065291  0.2404447   1.42147576  0.63101696 -0.4696834 ]
 [-0.50690834 -0.77121526  0.97392675 -0.93415406  0.36130359]
 [-0.80149137  0.10008462 -0.6095492  -1.02283344  0.71772743]
 [-0.30071031 -0.49173896  0.34644279 -0.56294359 -0.00682095]
 [ 0.87388379 -0.45025903  0.96993879  1.00328762  0.44651227]
 [-1.52064626  0.63942652  1.50947642 -0.65542821 -0.47115498]]


__Ejercicio__ La siguiente tabla muestra los resultados de el tiempo cronometrado por 10 distintas nadadadoras al nadar los 400 mts combinado en 20 competencias durante un año. Cada renglón corresponde a una nadadora y cada columna a un tiempo cronometrado. Para cada nadadora, encuentra

* El tiempo promedio y la varianza.
* El mejor tiempo obtenido para cada nadadora
* El promedio de los 5 mejores tiempos

Además, encuentra cuál nadadora obtuvo el mejor tiempo y cuál tuvo el mejor tiempo promedio

In [ ]:
# Tabla
import numpy as np
Tabla = np.full((10,20),290) + 20*np.random.random((10,20))
print(Tabla, np.shape(Tabla))


[[299.99878474 304.95964934 296.62304211 291.44924166 308.66383694
  302.82551522 306.59668294 309.38274495 291.05053423 306.34834668
  300.75930886 300.05959369 309.43470641 296.08782242 295.05564153
  290.05842644 304.34724164 298.46250534 304.21642916 300.83161998]
 [291.38694317 296.89513474 295.94626213 302.07665942 307.33769305
  308.63036548 305.02036615 290.26120447 296.99768399 306.77670291
  300.38252045 300.18071497 309.7659239  293.41469667 298.52087158
  300.28218762 303.95383145 296.09004527 293.19918158 296.74590471]
 [301.33640049 304.54606038 306.76333189 294.26792966 296.35399182
  307.65748447 296.86601046 296.31942869 308.24331004 298.48862706
  307.094311   301.10801716 309.19884543 297.06332831 303.71196504
  297.20764586 303.48541133 299.2611151  307.17733701 298.50003971]
 [295.86696114 301.34544344 303.04858909 292.12855889 294.27722304
  306.46827523 305.24869927 297.5012975  299.28442861 299.31108163
  293.36124218 295.26259966 297.76208205 309.83012111 297.9

In [ ]:
# Tu respuesta aquí


[300.86058371 299.69324469 301.73252955 299.46032333 301.59832415
 300.58548279 299.07876677 301.44343294 301.42965134 300.24012375] [34.86051398 31.74728738 21.96939303 28.69636101 36.91455313 21.9545339
 48.38971093 30.22999387 37.32507835 23.55691513]
