<a href="https://colab.research.google.com/github/ArianaMedina85/python/blob/main/Clase_Numpy_Tec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Notas (2025)

Esta unidad aborda de una manera mucho más detallada al lenguaje de programación Python para ser utilizado como herramienta de IA. Específicamente, se presentan distintos módulos en Python que facilitan la manipulación y mejoran la eficiencia al implementar funciones estadísticas y modelos matemáticos sobre un gran número de datos.

## Numpy ##

Numpy es una biblioteca que provee herramientas muy útiles para cómputo científico. Entre otras cosas, contiene:

* extensión para operaciones de alto desempeño con arreglos multidimensionales
* en general, sus operaciones son más eficientes (muchas vienen de funciones compiladas en c, es decir, un lenguaje bajo nivel).
* maneja contenedores utilizando de forma eficiente la memoria: espacios contiguos de memoria y por lo general más pequeños que un contenedor común de Python (así que es más rápido).
* está diseñado/pensado para cómputo científico (resulta conveniente). En particular, incluye algoritmos comúnes para operar sobre arreglos.

http://www.numpy.org/

### Primero importamos numpy ###

In [ ]:
import numpy as np
# Dos opciones menos recomendables:

#import numpy
#from numpy import *

Una característica clave de numpy es la existencia de sus arreglos multidimensionales, los cuales son contenedores rápidos y flexibles para datos. Estos arreglos son de un solo tipo de variable (necesario para poder ser eficientes).

#### Características de los arreglos multidimensionales ####

Algunos atributos importantes de los arreglos de numpy (ndarray):
    
    * ndarray.ndim - Número de dimensiones (número de ejes) del arreglo.
    * ndarray.shape - Tamaño de cada dimensión del arreglo, expresados como una tupla de enteros. Cada entero expresa el tamaño de una dimensión.
    * ndarray.size - Número total de elemento del arreglo. Es el producto del tamaño de cada dimensión.  
    * ndarray.dtype - Objeto que describe el tipo de elementos en el arreglo. Es posible especificarla al crear un arreglo. Además de los tipos regulares de Python, numpy incluye tipos de elementos como numpy.int32, numpy.int16, y numpy.float64, entre otros.
    * ndarray.itemsize - Tamaño en bytes de cada elemento del arreglo

#### ¿Cómo crear ndarrays? ####

In [ ]:
# Es posible convertir un contenedor en un arreglo de numpy

lista = [i for i in range(100)]

arrnp1 = np.array(lista)

print(f"arrnp1 es del tipo {type(arrnp1)}, y tiene una longitud de {arrnp1.size} \
y una forma de {arrnp1.shape} \n")

print(arrnp1)

arrnp1 es del tipo <class 'numpy.ndarray'>, y tiene una longitud de 100 y una forma de (100,) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


__Ejercicio de calentamiento__ Transforma la siguiente tupla en un arreglo de numpy.

In [6]:
tupla = (1,2,3,4,5)
# Tu código aquí
import numpy as np
array = np.array(tupla)
print (array)


[1 2 3 4 5]


In [ ]:
# También se puede crear directamente desde numpy

# Arreglo de 1's
arrnp2 = np.ones((3,4))
print(arrnp2)
print(f"arrnp2 tiene una longitud de {arrnp2.size} y una forma de {arrnp2.shape}")

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arrnp2 tiene una longitud de 12 y una forma de (3, 4)


In [ ]:
# Arreglo de 0's
arrnp3 = np.zeros((3,4))
print("\n****\n")
print(arrnp3)


****

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Arreglo de valores "aleatorios"
arrnp4 = np.random.random((3,4))
print("\n****\n")
print(arrnp4)


****

[[0.41189254 0.06010276 0.71554436 0.2150457 ]
 [0.18386516 0.21976461 0.0526811  0.49266359]
 [0.95048605 0.48241238 0.76145733 0.91920383]]


In [ ]:
# Arreglo vacío, pero tengan cuidado porque no asegura ningún valor
# y puede rellenar con cualquier basura que tenga en memora

arrnp5 = np.empty((3,4))
print("\n****\n")
print(arrnp5)


****

[[0.41189254 0.06010276 0.71554436 0.2150457 ]
 [0.18386516 0.21976461 0.0526811  0.49266359]
 [0.95048605 0.48241238 0.76145733 0.91920383]]


In [ ]:
# Arreglo lleno con el número pi

arrnp6 = np.full((3,4),np.pi)
print("\n****\n")
print(arrnp6)


****

[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]


__Ejercicio__ Utilizando numpy, crea una matriz de 5x5 cuyos elementos sean números "aleatorios" entre 0 y 1 (observa los ejemplos anteriores o revisa directamente la función random de numpy: https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html).

In [5]:
#Tu respuesta aqui
import numpy as np
array = np.random.random((5,5))
print(array)

[[0.5062819  0.33699313 0.5588902  0.73859683 0.913423  ]
 [0.7408998  0.42166654 0.83237665 0.48700008 0.40943207]
 [0.94961028 0.72812021 0.92601486 0.96716357 0.05240118]
 [0.29072013 0.90888655 0.98541886 0.2780236  0.60670506]
 [0.28916339 0.59912886 0.10824822 0.20957593 0.16514438]]


### Lógica de arreglos: operaciones aritméticas sobre arreglos ###

Los arreglos de numpy facilitan mucho el realizar operaciones en sus elementos, pues se sigue una lógica _element wise_ , o elemento-a-elemento. Esto evita el uso de ciclos para las operaciones.

In [ ]:
# Muchas de las operaciones en los arreglos de numpy tienen una lógica
# de elemento-a-elemento (element wise)

print("\nEste es el arreglo original:\n")
print(arrnp1)
print("\nY al sumar 1 al arreglo:\n")
print(arrnp1+1)


Este es el arreglo original:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Y al sumar 1 al arreglo:

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
# Todas las operaciones básicas, aplicadas a los arreglos de numpy, funcionan con esa lógica

print(arrnp1+arrnp1)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [ ]:
# Todas las operaciones básicas, aplicadas a los arreglos de numpy,
# funcionan con esa lógica

print(arrnp1*arrnp1)

print(arrnp1/arrnp1)

[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409
 9604 9801]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\glori\AppData\Local\Temp\ipykernel_23068\1706152686.py:6: RuntimeWarning: invalid value encountered in divide
  print(arrnp1/arrnp1)


__Ejercicio__ Para $x$ un arreglo de 10 elementos aleatorios, imprime el resultado de $2x$ utilizando numpy.

In [8]:
# Tu respuesta aquí
x= np.random.random((1,10))
x= 2*x
print(x)

[[0.88847091 0.76719971 1.3460432  0.13437431 1.47826124 0.21602079
  1.88013518 0.56922556 1.64832607 0.91141151]]


__Ejercicio__ Para $x$ un arreglo de 10 elementos aleatorios, realiza la suma $x + 10x^2$ utilizando numpy.

In [14]:
# Tu respuesta aquí
x= np.random.random((1,10))
print(x)
x= x+10*x**2
print(x)

[[0.4850724  0.99259459 0.42039105 0.30267213 0.36008807 0.16052008
  0.70348658 0.90951217 0.59887197 0.40080278]]
[[ 2.83802471 10.8450347   2.1876774   1.21877629  1.65672224  0.41818706
   5.65242026  9.18163613  4.18534833  2.00723148]]


__Ejercicio__ Utilizando contenedores de Python, crea la siguiente secuencia de 100 elementos: $2, 4, 6, \dots, 200$. Conviértelo en un arreglo de numpy y divide todos sus elementos entre 10.

In [ ]:
# Tu respuesta aquí. Recuerda las list comprehension.
#Comprehension
arreglo = [i for i in range(2,201,2)]
print(arreglo)

#otra forma
lista = list(range(2,201,2))
print(lista)

#otra forma
arr = [2*i for i in range(1,101)]
print(arr)


arrnp1 = np.array(lista)
res = arrnp1/10
print(res)




[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,

__Últimos dos ejemplos__ (para insistir en la idea de que Numpy me permite manejar arreglos multidimensionales de forma sencilla):

In [ ]:
# Por ejemplo:
val_ini, val_fin, paso = 15, 50, 0.5
a = np.arange(val_ini,val_fin, paso)     # Genero números en un rango, y espaciados como yo quiera
print(a)

[15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5
 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5
 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5
 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5
 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5]


In [ ]:
# Y ...
val_ini, val_fin, numero_de_puntos = 15, 50, 100
b = np.linspace(val_ini, val_fin,numero_de_puntos)   # Hago una partición de N elementos (100 en este caso), dentro de un rango
print(b, len(b))

[15.         15.35353535 15.70707071 16.06060606 16.41414141 16.76767677
 17.12121212 17.47474747 17.82828283 18.18181818 18.53535354 18.88888889
 19.24242424 19.5959596  19.94949495 20.3030303  20.65656566 21.01010101
 21.36363636 21.71717172 22.07070707 22.42424242 22.77777778 23.13131313
 23.48484848 23.83838384 24.19191919 24.54545455 24.8989899  25.25252525
 25.60606061 25.95959596 26.31313131 26.66666667 27.02020202 27.37373737
 27.72727273 28.08080808 28.43434343 28.78787879 29.14141414 29.49494949
 29.84848485 30.2020202  30.55555556 30.90909091 31.26262626 31.61616162
 31.96969697 32.32323232 32.67676768 33.03030303 33.38383838 33.73737374
 34.09090909 34.44444444 34.7979798  35.15151515 35.50505051 35.85858586
 36.21212121 36.56565657 36.91919192 37.27272727 37.62626263 37.97979798
 38.33333333 38.68686869 39.04040404 39.39393939 39.74747475 40.1010101
 40.45454545 40.80808081 41.16161616 41.51515152 41.86868687 42.22222222
 42.57575758 42.92929293 43.28282828 43.63636364 43.

### Indizado y slicing ###

Estos arreglos pueden ser n-dimensionales. Recordemos que las dimensiones de un arreglo se pueden consultar mediante arreglo.ndim

Cada dimensión tiene un tamaño, que corresponde al número de elementos que componen a esa dimensión. Por ejemplo, np.ones((3,4,2)) tiene 3 dimensiones, donde la primera dimensión tienen una longitud de 3, la segunda tiene una longitud de 4 y la tercera tienen una longitud de 2.  

__Ejemplo__ Para un arreglo uni-dimensional, el indizado y slicing funcionan de la misma forma que con una lista.

In [ ]:
# Arreglo de 3x1
arreglo = np.array([1.5, 2.5, 3.5, 2.1, 3.1, 4.1, 0.7, 1.7, 2.7])

print("Estos son todos los elementos del arreglo:")
print(arreglo)
print("")
print("Este es el 3er elemento del arreglo:")
print(arreglo[2])
print("")
print("Ahora van los primeros cuatro elementos:")
print(arreglo[0:4])
print("")
print("Ahora van los últimos cuatro elementos:")
print(arreglo[-4:])

Estos son todos los elementos del arreglo:
[1.5 2.5 3.5 2.1 3.1 4.1 0.7 1.7 2.7]

Este es el 3er elemento del arreglo:
3.5

Ahora van los primeros cuatro elementos:
[1.5 2.5 3.5 2.1]

Ahora van los últimos cuatro elementos:
[4.1 0.7 1.7 2.7]


__Ejercicio__ Utiliza slicing para sumar 1.3 a los tres últimos elementos del arreglo.

In [ ]:
arreglo = np.array([1.5, 2.5, 3.5, 2.1, 3.1, 4.1, 0.7, 1.7, 2.7])
arr2 = arreglo[-3:]
print(arr2)
arr2 = arr2+1.3
print(arr2)
# Tu código aquí
arreglo = [-3:] +=1.3 #arreglo[-3:] = arreglo[-3:]+1.3

#otra forma duplicar un arreglo
nvar= np.copy(arreglo[-3:])


[0.7 1.7 2.7]
[2. 3. 4.]


__Ejemplo__ Cuando se trata de un arreglo multidimensional, cada elemento es a su vez un arreglo. Veamos el caso de un arreglo de dos dimensiones.

In [ ]:
# Arreglo de 3x3: 2 dimensiones, cada una de longitud 3
arreglo = np.array([[1.5, 2.5, 3.5],[2.1, 3.1, 4.1],[0.7, 1.7, 2.7]])
print(arreglo)
print(arreglo.shape)
print(arreglo.ndim)

[[1.5 2.5 3.5]
 [2.1 3.1 4.1]
 [0.7 1.7 2.7]]
(3, 3)
2


In [ ]:
# Si imprimimos al elemento 0 del arreglo
arreglo = np.array([[1.5, 2.5, 3.5],[2.1, 3.1, 4.1],[0.7, 1.7, 2.7]])
print(arreglo)
print(arreglo[0])
print(arreglo[0].shape)
print(arreglo[0].ndim)

[[1.5 2.5 3.5]
 [2.1 3.1 4.1]
 [0.7 1.7 2.7]]
[1.5 2.5 3.5]
(3,)
1


Como cada elemento se trata a su vez de un arreglo, entonces se pueden utilizar índices para seleccionar elementos de dicho arreglo (y slicing).

In [ ]:
# Si imprimimos al elemento 0 del arreglo
arreglo = np.array([[1.5, 2.5, 3.5],[2.1, 3.1, 4.1],[0.7, 1.7, 2.7]])
print(arreglo[0])
print(arreglo[0][0])
print(arreglo[0,0])
print(arreglo[0][1:])
print(arreglo[0,1:])

[1.5 2.5 3.5]
1.5
1.5
[2.5 3.5]
[2.5 3.5]


En el caso específico de un arreglo de dos dimensiones, es válido pensarlo como un arreglo de renglones y columnas:

<img src="./Arreglo_tabla.png" alt="Drawing" style="width: 150px;"/>

In [ ]:
# Imprimo renglones
print(arreglo)
print("\n* Renglones *\n")
print(arreglo[0])
print("\n****\n")
print(arreglo[1])
print("\n****\n")
print(arreglo[2])

[[1.5 2.5 3.5]
 [2.1 3.1 4.1]
 [0.7 1.7 2.7]]

* Renglones *

[1.5 2.5 3.5]

****

[2.1 3.1 4.1]

****

[0.7 1.7 2.7]


In [ ]:
# Para acceder al otro eje, se puede utilizar una coma para separar el índice
print(arreglo)
print("\n* Columnas *\n")
print(arreglo[:,0])
print("\n****\n")
print(arreglo[:,1])
print("\n****\n")
print(arreglo[:,2])

[[1.5 2.5 3.5]
 [2.1 3.1 4.1]
 [0.7 1.7 2.7]]

* Columnas *

[1.5 2.1 0.7]

****

[2.5 3.1 1.7]

****

[3.5 4.1 2.7]


In [ ]:
print(arreglo)
nuva = arreglo[:,2]
print(nuva)
nuva += 2.3
print(nuva)
print(arreglo)
#print(arreglo[:,2])

[[1.5 2.5 3.5]
 [2.1 3.1 4.1]
 [0.7 1.7 2.7]]
[3.5 4.1 2.7]
[5.8 6.4 5. ]
[[1.5 2.5 5.8]
 [2.1 3.1 6.4]
 [0.7 1.7 5. ]]


__Ejercicio__ Modifica el arreglo del siguiente ejercicio, sumándole 1.0 a las columnas con índices pares.

In [ ]:
# Arreglo de 1's
arrnp2 = np.ones((3,4))
print(arrnp2)
arrnp2[:,0::2] +=1
print(arrnp2)
# Tu respuesta


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 1. 2. 1.]
 [2. 1. 2. 1.]
 [2. 1. 2. 1.]]


__Ejercicio__ Modifica el arreglo del siguiente ejercicio, sumándole 2.0 a las filas con índices impares

In [ ]:
# Arreglo de 1's
arrnp2 = np.ones((6,4))
print(arrnp2)
print()
arrnp2[1::2,:]
print(arrnp2)
print(arrnp2)
# Tu respuesta aquí


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Numpy es _veloz_ ###

__Ejemplo 1__ sobre la velocidad de numpy

In [ ]:
# Utilizando la magic function timeit, compara el tiempo que lleva ejecutar las siguientes dos versiones
# Elevar al cuadrado números en lista, versión normal Python
lini = [i for i in range(1000)]    # List comprehension para crear lista inicial
lno = [i**2 for i in lini]  # List comprehension para elevar al cuadrado cada elemento

# Utiliza timeit aquí para medir el tiempo que toma elevar al cuadrada cada elemento,
# utilizando una comprensión de lista
%timeit [i**2 for i in lini]
#magic funtcion timeit
# Elevar al cuadrado números dentro de arreglo numpy (mismo número de elementos que lista anterior)
import numpy as np           # Importo el módulo numpy con el nombre np
lini_nu = np.arange(1000)    # Creo un arreglo en numpy
lfin_nu = lini_nu**2         # Elevo al cuadrado cada elemento

# Utiliza timeit aquí para medir el tiempo que toma la misma operación,
# pero utilizando operaciones con numpy
%timeit lini_nu**2


161 μs ± 39.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.31 μs ± 1.08 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


__Ejemplo 2__ Generemos 100 puntos aleatorios dentro de un cubo cuyos lados valen 1, una de sus aristas coincide con el origen y se encuentra dentro del cuadrante definido por x > 0, y > 0, z > 0 en un espacio 3D. Calculemos después la distancia promedio de estos puntos con respecto al punto (1,0,0), y comparemos el tiempo que se necesita para calcular las distancias con numpy contra una forma más "tradicional".

In [ ]:
# observar funciones de numpy random.random y linalg.norm
import numpy as np
from random import random as rconv


def funnp():
    pos = np.random.random((100,3)) # <- 100 elementos con 3 componentes "aleatorias"
    vec = np.array([1,0,0])
    pos -= vec
    lisdis = np.linalg.norm(pos, axis=1) # a
    return lisdis

def funtrad():
    listav = []
    for i in range(100):
        vec = []
        for j in range(3):
            vec.append(rconv())
        listav.append(vec)
    for vector in listav:
        vector[0] -= 1.0
        vector[1] -= 0.0
        vector[2] -= 0.0
    lisdis = []
    for vector in listav:
        dist = 0.0
        for i in range(3):
            dist += vector[i]*vector[i]
        lisdis.append(np.sqrt(dist))
    return lisdis


%timeit funnp()
%timeit funtrad()

10.2 µs ± 243 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
142 µs ± 2.54 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
import random
with open("Datos_locos.dat", "w") as fout:
    fout.write("Un encabezado X\n")
    fout.write("Algunas especificaciones mega-útiles\n")
    for i in range(10000):
        fout.write(f"{random.random():.9f} \t {random.random():.9f} \t {random.random():.9f}\n")


# Es muy sencillo importar archivos con datos numéricos, y manipularlos
# En linux:
!head -3 ./Datos_locos.dat # Despliego primeras 5 líneas de archivo
!tail -1 ./Datos_locos.dat # Despliego primeras 5 líneas de archivo

# Ahora utilizo numpy para importarlo y sacarle información
dat1 = np.loadtxt("Datos_locos.dat", skiprows=2) # 2 líneas texto
print("\n")
print(f"El valor promedio de la primera columna: {np.average(dat1[:,0])}") # Obtengo promedio de la primera columna

# Ahora imprime el valor promedio de la 2da y 3ra columna, junto con su desviación estándar
# aquí tu código
print(f"El valor promedio de la segunda columna: {np.average(dat1[:,1])} +- {np.std(dat1[:,1])}")
print(f"El valor promedio de la tercera columna: {np.average(dat1[:,2])} +- {np.std(dat1[:,2])}")

Un encabezado X
Algunas especificaciones mega-útiles
0.937437973 	 0.200181154 	 0.477083038
0.501889240 	 0.419082527 	 0.373984672


El valor promedio de la primera columna: 0.5028826273758
El valor promedio de la segunda columna: 0.5011740163545001 +- 0.28888202068559404
El valor promedio de la tercera columna: 0.4984354994479 +- 0.2873761599847879


### Ejercicios extras ###

__Ejercicio__ Contesta las siguientes dos preguntas, tomando en cuenta el siguiente arreglo de numpy:

a = numpy.linspace(0,4,12).reshape(3,2,2)

_¿Cuántas dimensiones tiene el arreglo?_

_¿Qué tamaño tiene la última dimensión del arreglo?_


In [ ]:
# Tu respuesta aquí


__Ejercicio__ Utilizando numpy, crea la matriz identidad de 4x4

In [ ]:
# Tu respuesta aquí


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


__Ejercicio__ Utilizando numpy, crea una matriz diagonal con los elementos 5, 6, 7 y 8

In [ ]:
# Tu respuesta aquí


[[5 0 0 0]
 [0 6 0 0]
 [0 0 7 0]
 [0 0 0 8]]


__Ejercicio__ Utilizando numpy, crea un programa que calcule el ángulo que hay entre dos vectores (recordar definición geométrica del producto punto: https://es.wikipedia.org/wiki/Producto_escalar)


<img src="./Inner-product-angle.png" width="300"/>

In [ ]:
# Tu respuesta aquí


0 90.0


__Ejercicio__ Utilizando numpy y los arreglos definidos en la celda de abajo, a) suma el vector r a cada fila de la matriz, y b) suma el vector c a cada columna de la matriz.

In [ ]:
# Definición de arreglos
import numpy as np

mat = np.arange(12).reshape((4,3))
r = np.array(range(1,4))
c = np.array([1,0,0,0])

print(mat)
print(r)
print(c)

# a) Tu respuesta aquí


# b) Tu respuesta aquí


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[1 2 3]
[1 0 0 0]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]
[[ 2  4  6]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]
