<a href="https://colab.research.google.com/github/ArianaMedina85/python/blob/main/RepasoNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#instrucciones básicas de NumPy*, una librería fundamental para trabajar con arrays y operaciones matemáticas en Python.

## 1. Instalación y Importación

In [31]:

# Importar
import numpy as np


## 2. Crear Arrays

In [32]:
import numpy as np

# Array de una lista
arr1 = np.array([1, 2, 3, 4])          # array([1, 2, 3, 4])

# Array de ceros
zeros = np.zeros((2, 3))               # array([[0., 0., 0.], [0., 0., 0.]])

# Array de unos
unos = np.ones((3, 2))                 # array([[1., 1.], [1., 1.], [1., 1.]])

# Rango de números (similar a range)
rango = np.arange(0, 10, 2)            # array([0, 2, 4, 6, 8])

# Espaciado lineal
lin = np.linspace(0, 1, 5)             # array([0.  , 0.25, 0.5 , 0.75, 1.  ])


## 3. Propiedades de un Array

In [29]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)    # (2, 3)  -> dimensiones
print(arr.ndim)     # 2       -> número de dimensiones
print(arr.dtype)    # int64   -> tipo de datos
print(arr.size)     # 6       -> total de elementos


(2, 3)
2
int64
6


## 4. Acceso y Modificación

In [28]:

arr = np.array([10, 20, 30, 40, 50])

# Indexación
print(arr[2])       # 30
print(arr[1:4])     # array([20, 30, 40])

# Modificar
arr[0] = 100
arr[1:3] = [200, 300]


30
[20 30 40]


## 5. Operaciones Básicas (elemento a elemento)

In [27]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)        # array([5, 7, 9])   -> suma
print(a * b)        # array([ 4, 10, 18]) -> multiplicación
print(a ** 2)       # array([1, 4, 9])    -> potencia
print(np.sqrt(a))   # array([1., 1.414, 1.732]) -> raíz cuadrada


[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]


##6. Funciones Útiles

In [26]:

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))      # 15           -> suma total
print(np.mean(arr))     # 3.0          -> promedio
print(np.max(arr))      # 5            -> máximo
print(np.min(arr))      # 1            -> mínimo
print(np.std(arr))      # 1.414        -> desviación estándar


15
3.0
5
1
1.4142135623730951


# 7. Cambiar Forma (reshape) y Transponer

In [25]:

arr = np.arange(6)      # array([0, 1, 2, 3, 4, 5])
arr_reshaped = arr.reshape(2, 3)  # array([[0, 1, 2], [3, 4, 5]])

# Transponer
trans = arr_reshaped.T  # array([[0, 3], [1, 4], [2, 5]])


8. Concatenar y Dividir

In [24]:

a = np.array([1, 2])
b = np.array([3, 4])

# Concatenar
concat = np.concatenate((a, b))  # array([1, 2, 3, 4])

# Dividir
x = np.array([1, 2, 3, 4, 5, 6])
split = np.split(x, 3)  # [array([1, 2]), array([3, 4]), array([5, 6])]
#Esas son las operaciones más básicas y útiles de NumPy.
